version: '3.8'

services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: recipe-mysql-prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-1234}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-cookwise}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - recipe-network

  # QDRANT 벡터 데이터베이스
  qdrant:
    image: qdrant/qdrant:latest
    container_name: recipe-qdrant-prod
    ports:
      - "6201:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - recipe-network

  # FastAPI 백엔드 (Docker Hub 이미지 사용)
  backend:
    image: ${DOCKER_HUB_USERNAME}/my-recipe-app-backend:latest
    container_name: recipe-backend-prod
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:${MYSQL_ROOT_PASSWORD:-1234}@mysql:3306/${MYSQL_DATABASE:-cookwise}
      - QDRANT_URL=http://qdrant:6333
      - ENV=production
      - FOOD_SAFETY_API_KEY=${FOOD_SAFETY_API_KEY}
      - FOOD_SAFETY_SERVICE_ID=${FOOD_SAFETY_SERVICE_ID:-COOKRCP01}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
    depends_on:
      mysql:
        condition: service_healthy
      qdrant:
        condition: service_started
    volumes:
      - ./backend/hf_cache:/app/hf_cache
    networks:
      - recipe-network

  # Next.js 프론트엔드 (Docker Hub 이미지 사용)
  frontend:
    image: ${DOCKER_HUB_USERNAME}/my-recipe-app-frontend:latest
    container_name: recipe-frontend-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - recipe-network

  # Nginx 리버스 프록시 (선택사항)
  nginx:
    image: nginx:alpine
    container_name: recipe-nginx-prod
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - recipe-network
    profiles:
      - nginx

volumes:
  mysql_data:
  qdrant_data:

networks:
  recipe-network:
    driver: bridge 